### PR TITLE
Account apps and redirect

### PR DESCRIPTION
**Pull request by avojnovicDk**

### CODE REVIEW

**Comment by denibertovic** [comment]
awesome stuff @avojnovicDk :+1: 

BTW @rdegges this fixes the "recursion" error that we are seeing on Travis at the moment. 
However, This doesn't seem like a SDK issue. Specifically, the tests will most likely fail again but this time the SDK will report a proper error message. 

So, what's happening is that the API is for some reason complaining that some requests are not authenticated and redirecting to the Login page (the html version). This shouldn't happen, the API should either return 403 or something but not redirect the user to a html page (this caused an endless redirect loop in the SDK).

**Comment by denibertovic** [comment]
(we should probably try and re-run the tests to get them to fail so that you see the error first hand....unless this was a fluke and was fixed on the API in the mean time).

**Comment by rdegges** [comment]
Thanks @avojnovicDk and @denibertovic. This makes a lot of sense. I'm going to talk with Les about this today... Super weird.

Glad we have some tests / behaviors in there to look for this now though (just incase!).

Also: thanks for adding Account.applications. Love that! <33

**Comment by rdegges** [comment]
Actually -- @denibertovic, could this somehow be that we're not setting content-type: application/json? That's the only other reason I can think of oO

Is there any edge case where that might happen? That would most definitely cause us to 302 to /login (like a web user).

**Comment by rdegges** [comment]
Debugging this a bit further -- it seems I can't reproduce this myself... However... Looking at the test results, it seems this is definitely an issue in our code somewhere.

Check this out: 
screenshot 2015-01-23 11 49 32

It looks as if there is some weirdness with some of our underlying API calls, as our method / urls are incorrect. I think this is the root of the issue.

@avojnovicDk & @denibertovic would you  mind looking into this?

**Comment by denibertovic** [comment]
@rdegges yeah we think we know where the issue is. @avojnovicDk will do a PR with a fix soon.

**Comment by denibertovic** [comment]
@rdegges FWIW I don't think the redirect to login has anything to do with content-type as it's hardcoded directly on the HttpExecutor to application/json. There's definitely a bug in the above screenshot and this will be fixed but I'm not sure this has anything to with the redirect to the web user login page.

**Pull request merged**
