### PR TITLE
Password policy directories

### PR DESCRIPTION
**Pull request by avojnovicDk**
Added PasswordPolicy resource for Directory.
(Issue #129)

### CODE REVIEW

**Comment by rdegges** [comment]
Hey @avojnovicDk, thanks so much! This is excellent codez. Super clean. Love it.

I have one minor API change which I think should be implemented before accepting this PR. I think we should redo the way this works: http://i.imgur.com/7Hk96Kl.png

Essentially, right now, the `default_model` dictionary that holds the base url setting can only hold that single setting.

The future plan, however, is to allow users to put any sorta of JSON data in there -- and have this data be passed into the email template as variables (this is what we're implementing currently).

I think that what we should do, to support this new behavior in the future, is just let the user modify `default_model` directly, treating it like a normal Python dictionary and letting the user set / update / override whatever they want in there without restriction.

That would be fine for now, as even if the user adds any custom stuff in there other than the base url, we won't do anything with it and won't complain.

**Comment by avojnovicDk** [comment]
Hi @rdegges! I made default_model writable, and left the get_() and set_() functions for convenience. Please take a look at it.

**Comment by omgitstom** [comment]
@rdegges This is ready for review again

**Comment by rdegges** [comment]
Merged in, cutting a new release now =)

**Comment by rdegges** [comment]
Hmm, actually, before I cut a release.

@avojnovicDk can you fix some of the Python 3 issues? eg: https://travis-ci.org/stormpath/stormpath-sdk-python/jobs/52318689

If you open a new PR with the fixes I'll get that merged in ASAP and cut a final release.

**Comment by avojnovicDk** [comment]
Hey @rdegges, here is the fix for the Python 3 issues. Strange, that didn't fail before it was merged.

**Comment by senko** [comment]
It's not strange - the live tests on Travis are *only* done in master branch - not for pull requests.

This has to do with Travis security feature of not allowing environment variables (needed for live tests) to be used in pull requests or other branches.

**Comment by senko** [comment]
However, this *does* mean we should make sure we test on Python 2.7 *and* Python 3.x locally, not just trust Travis.

**Comment by rdegges** [comment]
Thanks @avojnovicDk and @senko =)

**Pull request merged**
