### PR TITLE
Added leeway on jwt.decode() calls and tests for it.

### PR DESCRIPTION
**Pull request by avojnovicDk**
This is temporary fix for minor clock skews, as advised in https://github.com/stormpath/stormpath-sdk-python/issues/226#issuecomment-156182755 .

### CODE REVIEW

**Comment by rdegges** [comment]
This looks good -- but can we get the 2 second thing defined as a global in here with some comments around it? I wanna make sure it's easy to understand in the source later on. Will merge after change <3

**Comment by avojnovicDk** [comment]
Thanks for the comment @rdegges ! I've added variable and comments.

**Comment by rdegges** [comment]
Thanks! =)

**Comment by rdegges** [comment]
Just cut a new release with this included.

**Pull request merged**
