### PR TITLE
A couple of fixes and features

### LINKED ISSUE #102: Add Support for len(CollectionResource)
Right now, calling len() on any collection resource results in an invalid credentials error, for instance:

```python
>>> from stormpath.client import Client
>>> from stormpath.resources.account import Account
>>> client = Client(api_key_file_location='apiKey.properties')
>>> for app in c.applications:
>>>     print app.name
>>> results = app.accounts.search({'username': 'rdegges'})
>>> len(results)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stormpath/resources/base.py", line 433, in __len__
    self._ensure_data()
  File "stormpath/resources/base.py", line 270, in _ensure_data
    data = self._store.get_resource(self.href, params=params)
  File "stormpath/data_store.py", line 122, in get_resource
    data = self.executor.get(href, params=params)
  File "stormpath/http.py", line 91, in get
    return self.request('GET', url, params=params)
  File "stormpath/http.py", line 81, in request
    raise Error(r.json(), http_status=r.status_code)
stormpath.error.Error: Authentication with a valid API Key is required.
```

It looks like we're not properly handling this.

FYI -- we recently added a new 'size' attribute to all CollectionResource responses.

For instance, if you query the rest API for accounts on an application, you'll see we now return a 'size' property (which is an integer), that reflects how many total items are in the collection.

This could be really useful here =)

### LINKED ISSUE #107: Exponential Backoff?
In regards to #106, I'm wondering if we should implement exponential backoff in our client -- this would be sort of nice, as any 5xx errors will get retried automatically after a short wait. This would improve client application stability in a 'clean' way -- and would still allow people to make async use of the library with stuff like gevent.

Any thoughts?

### LINKED ISSUE #110: InvalidAudienceError in Application.handle_id_site_callback
When the jwt token from the url is decoded by jwt.decode, it throws an invalid audience error if there is an 'aud' field in the payload but no audience passed in:
```
def decode(jwt, key='', verify=True, **kwargs):
    payload, signing_input, header, signature = load(jwt)

    if verify:
        verify_signature(payload, signing_input, header, signature, key,
                         **kwargs)

    return payload
```
...
```
def verify_signature(payload, signing_input, header, signature, key='',
                     verify_expiration=True, leeway=0, audience=None,
                     issuer=None):
    ...
    if 'aud' in payload:
        audience_claims = payload['aud']
        if isinstance(audience_claims, string_types):
            audience_claims = [audience_claims]
        if not isinstance(audience_claims, list):
            raise InvalidAudienceError('Invalid claim format in token')
        if any(not isinstance(c, string_types) for c in audience_claims):
            raise InvalidAudienceError('Invalid claim format in token')
        if audience not in audience_claims:
            raise InvalidAudienceError('Invalid audience')
```

The stormpath application handle_id_site_callback function doesn't pass in an audience kwarg to jwt.decode, so if there is an 'aud' in the payload from stormpath (and currently there is, it contains my stormpath api id) it will never verify. I think this has been overlooked since the exception goes uncaught:

stormpath.resources.application.py:
```
def handle_id_site_callback(self, url_response):
    ...
    api_key_secret = self._client.auth.secret

    # validate signature
        try:
            decoded_data = jwt.decode(jwt_response, api_key_secret)
        except (jwt.DecodeError, jwt.ExpiredSignature):
            return None
    ...
```

I can fix it for my site by modifying application.py to this:

```
        api_key_secret = self._client.auth.secret
        api_key_id = self._client.auth.id

        # validate signature
        try:
            decoded_data = jwt.decode(jwt_response, api_key_secret, audience=api_key_id)
        except (jwt.DecodeError, jwt.ExpiredSignature):
            return None
```

but heroku for some reason refuses to install my fork and defaults to using the package, so at the minute my application can't handle logins and logouts.

### PR DESCRIPTION
**Pull request by denibertovic**
This adds the following features and fixes:

* Backoff strategy (Closes #107)
* Fixes InvalidAudienceError in Application.handle_id_site_callback  (closes #110)
* Fixes collection issues with Sauthc1 (closes #102 and #101)

### CODE REVIEW

**Comment by rdegges** [comment]
This looks great, thank you =)

**Comment by rdegges** [comment]
Hmm, actually -- it looks like this can't be merged. Can you take a look at the errors?

**Comment by denibertovic** [comment]
argh...this is still broken. looking into it.

**Comment by denibertovic** [comment]
@rdegges okay I've finally fixed the tests and merge conflicts on this. Once this is merged we can close #107 and #110

**Comment by denibertovic** [comment]
@rdegges update the title and description to list all the issues fixed here and what to close.

**Comment by rdegges** [comment]
Oh man, great work everyone. This solves so many issues. Really appreciate everyone's hard work on this.

**Comment by rdegges** [comment]
@denibertovic hmm, I just merged this stuff in, but we're having some issues with tests / recursion. See: https://travis-ci.org/stormpath/stormpath-sdk-python

Any idea?

**Comment by denibertovic** [comment]
@rdegges hmmm...that's weird. Looking into it.

**Comment by rdegges** [comment]
Welp, looks like this is all fixed now via the other PRs. Going to start cutting a new release. Thank you for your help!

**Pull request merged**
