### PR TITLE
Custom data caching

### PR DESCRIPTION
**Pull request by avojnovicDk**
I enabled customData caching. Along the way, I found bug with multiple deletion of custom data items and fixed it. More detailed descriptions are in commit messages.

### CODE REVIEW

**Comment by denibertovic** [comment]
@avojnovicDk there seem to be some merge conflicts. Can you rebase on the current develop branch?

**Comment by denibertovic** [comment]
apart from that LGTM. cc @rdegges

**Comment by rdegges** [comment]
Hey @avojnovicDk looks good to me! Can ya fix those merge conflicts though? Happy to merge! <33

**Comment by denibertovic** [comment]
:+1:

**Comment by rdegges** [comment]
Thans @avojnovicDk and @denibertovic! Ya'll are awesome.

**Pull request merged**
